# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed2c32df9873e398c48f33859900ead93218d06a5dcc3d459c35b01d89512864993f0f91006a888c6d4fc1d322bf41922b0997f4f196df4157062b7df748785e

test:
  secret_key_base: 2ea553bdb553ecf0d039401343ac347105e179fea76f25302f70a19337b904c67946f22f356dfa3659d2cef600c583ad7ee7bc842adfdb8edf9af29c5eb9f5e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
